### PR TITLE
Update documentation frontmatter

### PR DESCRIPTION
**Pull request by philgomes**
Updated tldr.

Features section now focuses on benefits.

### CODE REVIEW

**Review by rmilrad — APPROVED** [review]

**Review by rmilrad — APPROVED** [review]
Approved

**Comment by rmilrad** [comment]
@jcvernaleo Can you see if you can approve these changes? Im not sure how Gitbook coincides with Github here. Looks like it requires additional approval

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by philgomes** [comment]
My first accepted Hemi pull request.

Neat.

**Comment by jcvernaleo** [comment]
First of many hopefully :)

**Pull request merged**
